### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by PRINCEHR** [proyecto26/PokeDex-GO#2]
Failed to restore plugin "com.verso.cordova.clipboard" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin https://github.com/VersoSolutions/CordovaClipboard.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  git+https://github.com/VersoSolutions/CordovaClipboard.git resetting remote C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-VersoSolutions-CordovaClipboard-git-cc77f7f7 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/VersoSolutions/CordovaClipboard.git C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-VersoSolutions-CordovaClipboard-git-cc77f7f7: Cloning into bare repository 'C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-VersoSolutions-CordovaClipboard-git-cc77f7f7'...
npm ERR! git clone --template=C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/VersoSolutions/CordovaClipboard.git C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-VersoSolutions-CordovaClipboard-git-cc77f7f7: fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/VersoSolutions/CordovaClipboard.git" "--production" "--no-save"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/VersoSolutions/CordovaClipboard.git C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-VersoSolutions-CordovaClipboard-git-cc77f7f7
npm ERR! Cloning into bare repository 'C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-VersoSolutions-CordovaClipboard-git-cc77f7f7'...
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\g_apps\POKEDEX GO\npm-debug.log
Discovered plugin "cordova-plugin-file-transfer" in config.xml. Adding it to the project
Installing "cordova-plugin-file-transfer" for android
Failed to install 'cordova-plugin-file-transfer': CordovaError: Version of installed plugin: "cordova-plugin-file@4.3.3" does not satisfy dependency plugin requirement "cordova-plugin-file@>=5.0.0". Try --force to use installed plugin as dependency.
    at C:\Users\ekdantay\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:557:37
    at _fulfilled (C:\Users\ekdantay\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\ekdantay\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\ekdantay\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\ekdantay\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
    at flush (C:\Users\ekdantay\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Failed to restore plugin "cordova-plugin-file-transfer" from config.xml. You might need to try adding it again. Error: Version of installed plugin: "cordova-plugin-file@4.3.3" does not satisfy dependency plugin requirement "cordova-plugin-file@>=5.0.0". Try --force to use installed plugin as dependency.

Discovered plugin "cordova-plugin-x-toast" in config.xml. Adding it to the project
Failed to restore plugin "cordova-plugin-x-toast" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin git+https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit  git+https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git resetting remote C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-EddyVerbruggen-Toast-PhoneGap-Plugin-git-3ed6ea7d because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-EddyVerbruggen-Toast-PhoneGap-Plugin-git-3ed6ea7d: Cloning into bare repository 'C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-EddyVerbruggen-Toast-PhoneGap-Plugin-git-3ed6ea7d'...
npm ERR! git clone --template=C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-EddyVerbruggen-Toast-PhoneGap-Plugin-git-3ed6ea7d: fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "git+https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git" "--production" "--no-save"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-EddyVerbruggen-Toast-PhoneGap-Plugin-git-3ed6ea7d
npm ERR! Cloning into bare repository 'C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-EddyVerbruggen-Toast-PhoneGap-Plugin-git-3ed6ea7d'...
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\g_apps\POKEDEX GO\npm-debug.log
Discovered plugin "ionic-plugin-deploy" in config.xml. Adding it to the project
Failed to restore plugin "ionic-plugin-deploy" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin git+https://github.com/driftyco/ionic-plugins-deploy.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit  git+https://github.com/driftyco/ionic-plugins-deploy.git resetting remote C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-driftyco-ionic-plugins-deploy-git-51680edd because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/driftyco/ionic-plugins-deploy.git C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-driftyco-ionic-plugins-deploy-git-51680edd: Cloning into bare repository 'C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-driftyco-ionic-plugins-deploy-git-51680edd'...
npm ERR! git clone --template=C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/driftyco/ionic-plugins-deploy.git C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-driftyco-ionic-plugins-deploy-git-51680edd: fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "git+https://github.com/driftyco/ionic-plugins-deploy.git" "--production" "--no-save"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/driftyco/ionic-plugins-deploy.git C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-driftyco-ionic-plugins-deploy-git-51680edd
npm ERR! Cloning into bare repository 'C:\Users\ekdantay\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-driftyco-ionic-plugins-deploy-git-51680edd'...
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\g_apps\POKEDEX GO\npm-debug.log

ANDROID_HOME=C:\Users\ekdantay\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_92
:wrapper

BUILD SUCCESSFUL

Total time: 25.393 secs

Subproject Path: CordovaLib
Starting a Gradle Daemon (subsequent builds will be faster)
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_7j2vn0922y9xww45ri6y5a5vx.run(F:\g_apps\POKEDEX GO\platforms\android\build.gradle:143)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.

Download https://maven.google.com/com/google/android/gms/play-services-ads/15.0.1/play-services-ads-15.0.1.pom
Download https://maven.google.com/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.pom

Download https://maven.google.com/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.pom
Download https://maven.google.com/com/android/support/customtabs/26.1.0/customtabs-26.1.0.pom

Download https://maven.google.com/com/google/android/gms/play-services-ads-base/15.0.1/play-services-ads-base-15.0.1.pom

Download https://maven.google.com/com/google/android/gms/play-services-ads-identifier/15.0.1/play-services-ads-identifier-15.0.1.pom

Download https://maven.google.com/com/google/android/gms/play-services-ads-lite/15.0.1/play-services-ads-lite-15.0.1.pom
Download https://maven.google.com/com/google/android/gms/play-services-gass/15.0.1/play-services-gass-15.0.1.pom

Download https://maven.google.com/com/google/android/gms/play-services-auth-api-phone/11.8.0/play-services-auth-api-phone-11.8.0.pom

Download https://maven.google.com/com/google/android/gms/play-services-auth-base/11.8.0/play-services-auth-base-11.8.0.pom

Download https://maven.google.com/com/google/android/gms/play-services-identity-license/11.8.0/play-services-identity-license-11.8.0.pom

Download https://maven.google.com/com/google/android/gms/play-services-auth-api-phone-license/11.8.0/play-services-auth-api-phone-license-11.8.0.pom

Download https://maven.google.com/com/google/android/gms/play-services-auth-base-license/11.8.0/play-services-auth-base-license-11.8.0.pom

Download https://maven.google.com/com/android/support/customtabs/26.1.0/customtabs-26.1.0.aar

Download https://maven.google.com/com/google/android/gms/play-services-ads-base/15.0.1/play-services-ads-base-15.0.1.aar

Download https://maven.google.com/com/google/android/gms/play-services-ads-identifier/15.0.1/play-services-ads-identifier-15.0.1.aar

Download https://maven.google.com/com/google/android/gms/play-services-ads-lite/15.0.1/play-services-ads-lite-15.0.1.aar

Download https://maven.google.com/com/google/android/gms/play-services-gass/15.0.1/play-services-gass-15.0.1.aar

Download https://maven.google.com/com/google/android/gms/play-services-ads/15.0.1/play-services-ads-15.0.1.aar

Download https://maven.google.com/com/google/android/gms/play-services-auth-api-phone-license/11.8.0/play-services-auth-api-phone-license-11.8.0.aar

Download https://maven.google.com/com/google/android/gms/play-services-auth-api-phone/11.8.0/play-services-auth-api-phone-11.8.0.aar

Download https://maven.google.com/com/google/android/gms/play-services-auth-base-license/11.8.0/play-services-auth-base-license-11.8.0.aar

Download https://maven.google.com/com/google/android/gms/play-services-auth-base/11.8.0/play-services-auth-base-11.8.0.aar

Download https://maven.google.com/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.aar

Download https://maven.google.com/com/google/android/gms/play-services-identity-license/11.8.0/play-services-identity-license-11.8.0.aar

Download https://maven.google.com/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.aar

:preBuild

UP-TO-DATE
:preDebugBuild
 UP-TO-DATE
:checkDebugManifest

:preReleaseBuild
 UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl

:CordovaLib:compileDebugNdk

UP-TO-DATE
:CordovaLib:compileLint

:CordovaLib:copyDebugLint

UP-TO-DATE
:CordovaLib:mergeDebugShaders

:CordovaLib:compileDebugShaders

:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets

:CordovaLib:mergeDebugProguardFiles

:CordovaLib:packageDebugRenderscript

UP-TO-DATE
:CordovaLib:compileDebugRenderscript

:CordovaLib:generateDebugResValues

:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources

:CordovaLib:processDebugManifest

:CordovaLib:generateDebugBuildConfig

:CordovaLib:processDebugResources

:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard

:CordovaLib:compileDebugJavaWithJavac

:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes
 UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug

:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug

:CordovaLib:mergeDebugJniLibFolders

:CordovaLib:transformNative_libsWithMergeJniLibsForDebug

:CordovaLib:transformNative_libsWithSyncJniLibsForDebug

:CordovaLib:bundleDebug

:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest

:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl

:CordovaLib:compileReleaseNdk

UP-TO-DATE
:CordovaLib:copyReleaseLint
 UP-TO-DATE

:CordovaLib:mergeReleaseShaders

:CordovaLib:compileReleaseShaders

:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets

:CordovaLib:mergeReleaseProguardFiles

:CordovaLib:packageReleaseRenderscript
 UP-TO-DATE

:CordovaLib:compileReleaseRenderscript

:CordovaLib:generateReleaseResValues

:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources

:CordovaLib:processReleaseManifest

:CordovaLib:generateReleaseBuildConfig

:CordovaLib:processReleaseResources

:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard

:CordovaLib:compileReleaseJavaWithJavac

:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes
 UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease

:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease

:CordovaLib:mergeReleaseJniLibFolders

:CordovaLib:transformNative_libsWithMergeJniLibsForRelease

:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease

:prepareAndroidArchCoreRuntime110Library

:prepareAndroidArchLifecycleLivedataCore110Library

:prepareAndroidArchLifecycleRuntime110Library

:prepareAndroidArchLifecycleViewmodel110Library

:prepareBarcodescannerLibrary

:prepareComAndroidSupportAsynclayoutinflater2800Alpha1Library

:prepareComAndroidSupportCoordinatorlayout2800Alpha1Library

:prepareComAndroidSupportCursoradapter2800Alpha1Library

:prepareComAndroidSupportCustomtabs2610Library

:prepareComAndroidSupportCustomview2800Alpha1Library

:prepareComAndroidSupportDocumentfile2800Alpha1Library

:prepareComAndroidSupportDrawerlayout2800Alpha1Library

:prepareComAndroidSupportInterpolator2800Alpha1Library

:prepareComAndroidSupportLoader2800Alpha1Library

:prepareComAndroidSupportLocalbroadcastmanager2800Alpha1Library

:prepareComAndroidSupportPrint2800Alpha1Library

:prepareComAndroidSupportSlidingpanelayout2800Alpha1Library

:prepareComAndroidSupportSupportCompat2800Alpha1Library

:prepareComAndroidSupportSupportCoreUi2800Alpha1Library

:prepareComAndroidSupportSupportCoreUtils2800Alpha1Library

:prepareComAndroidSupportSupportFragment2800Alpha1Library

:prepareComAndroidSupportSupportMediaCompat2800Alpha1Library

:prepareComAndroidSupportSupportV42800Alpha1Library

:prepareComAndroidSupportSwiperefreshlayout2800Alpha1Library

:prepareComAndroidSupportViewpager2800Alpha1Library

:prepareComGoogleAndroidGmsPlayServicesAds1501Library

:prepareComGoogleAndroidGmsPlayServicesAdsBase1501Library

:prepareComGoogleAndroidGmsPlayServicesAdsIdentifier1501Library

:prepareComGoogleAndroidGmsPlayServicesAdsLite1501Library

:prepareComGoogleAndroidGmsPlayServicesAuth1180Library

:prepareComGoogleAndroidGmsPlayServicesAuthApiPhone1180Library

:prepareComGoogleAndroidGmsPlayServicesAuthApiPhoneLicense1180Library

:prepareComGoogleAndroidGmsPlayServicesAuthBase1180Library

:prepareComGoogleAndroidGmsPlayServicesAuthBaseLicense1180Library

:prepareComGoogleAndroidGmsPlayServicesBase1180Library

:prepareComGoogleAndroidGmsPlayServicesBaseLicense1180Library

:prepareComGoogleAndroidGmsPlayServicesBasement1501Library

:prepareComGoogleAndroidGmsPlayServicesGass1501Library

:prepareComGoogleAndroidGmsPlayServicesIdentity1180Library

:prepareComGoogleAndroidGmsPlayServicesIdentityLicense1180Library

:prepareComGoogleAndroidGmsPlayServicesTasks1180Library

:prepareComGoogleAndroidGmsPlayServicesTasksLicense1180Library

:prepareOrgApacheCordovaCordovaLib630DebugLibrary

:prepareDebugDependencies
:compileDebugAidl

:compileDebugRenderscript

:generateDebugBuildConfig

:generateDebugResValues

:generateDebugResources
:mergeDebugResources

:processDebugManifest

:processDebugResources
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 30.673 secs
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] An error occurred while running cordova build android (exit code 1).

**Comment by jdnichollsc** [comment]
try removing and adding that plugin again
